# Generated by Django 3.0.3 on 2020-02-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailored', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='avatar',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='shoot',
            name='image',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='photo_url',
            field=models.TextField(default=''),
        ),
    ]
