# Generated by Django 3.0.3 on 2020-02-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailored', '0002_auto_20200221_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='shoot',
            name='category',
        ),
        migrations.AddField(
            model_name='shoot',
            name='category',
            field=models.ManyToManyField(to='tailored.Category'),
        ),
    ]
