# Generated by Django 3.0.3 on 2020-02-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailored', '0003_auto_20200224_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
